### ISSUE TITLE
Better support of notes with many cards

### ISSUE THREAD

**Issue by aleksejrs** [lovac42/PushParadox#2]
The problem: there are notes with **many** cards that are simply pre-existing (old or taken from a downloaded deck), or made using an add-on like Cloze Overlapper (up to 21 cards by default, but any number of cards can be added by the user). Any additional burying can make such notes take months or years to learn. Notes with just 4-6 cards can also suffer.

I want certain notes to be ready in days or weeks, but Push Paradox should work for other notes.

Cloze Overlapper tries to solve this by optionally overriding burying for its note type (separate checkboxes for new and review cards). But I don't need that for *all* CO cards. I haven't tested properly how that option affects PP: it doesn't matter. I could make a separate CO note type and edit Push Paradox to skip cards of that type, but that's certainly not a flexible way to work with priorities (I use [this one](https://github.com/aleksejrs/anki-priofiltergenerator) — in Russian and undocumented — which creates filtered decks and search queries), and though it's most likely possible to use the same priority queries I use for filtering, it would be too hard for me, require big edits to the add-on, and not be useful for others.

# Solution 

Overview:

*deadline* → *total days* → **days per card** → *Sibling IVL*

* "*Sibling IVL*" is what PP is using.
* "**days per card**" is how many days a card is allowed to take before another card is introduced.
* "*total days*" is the total number of days to introduce all cards, or to introduce all cards AND let them reach a certain level of maturity. That level should probably equal **days per card**; if the note is too important for that, it could have a *deadline* field.
* An additional link in the chain is "deadline", an optional value in a special field of a card which can be used to calculate *total days* based on today's date.

The hardest part is converting **days per card** into *Sibling IVL*. Maybe in some cases PP should just ignore cards that have achieved the **days per card** value since First Review.

For example, if a note has non-suspended 5 cards (or 5 non-suspended new cards, see below), and *total days* is 30 days, there are 6 days per card. Take the interval that a card achieves in 6 days, on average, round it down, and use that as the Sibling IVL value.

## Questions:
* Where do you get *total days* from (mentioned above with "a certain level of maturity")?
* When there is no "deadline", should PP use the "total days" for all non-suspended cards of the note, or only the new non-suspended cards of the note?

**Comment by lovac42** [comment]
I think you have the wrong idea of how this addon works or how it's coded. It sounds like you are asking for sibling spacing, which is also what CO uses to spread the siblings. Search for SS on ankiweb.

This addon just checks any sibling with a specified interval and bury it if any exists. So say you choose sibling ivl of 5, if any of the review or lapsed siblings have less than ivl of 5, the current NEW card will be buried. This prevents two young cards from being studied close together. And you can separate siblings into different decks for alternative deck scanning options. Anything more than that will be distorting the algorithm, which I am strongly against.
